data:
    root: '../pytorch-superpoint/datasets/TLS_Train/synthetic_shapes_v6' # # /content/drive/MyDrive
    preprocessing:
        resize: [320, 216]  # width, height
        # resize: [480, 640]
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 30}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false
            num: 1 # 100
            aggregation: 'sum'
            filter_counts: 0
            homographies:
                params:
                    translation: true
                    rotation: true
                    scaling: false
                    perspective: true
                    scaling_amplitude: 1
                    perspective_amplitude_x: 0.3
                    perspective_amplitude_y: 0.3
                    allow_artifacts: true
                    patch_ratio: 0.85
                    max_angle: 0.785
        valid_border_margin: 3

model:
    batch_size: 1 # 32
    detection_threshold: 0.015 # 0.015
    nms: 1
    descriptor_dist: 8 # 4, 7.5
    epsilon: 3

pretrained: "../my_superpoint_pytorch/colab_log/magicpoint.pt"



